@api =http://localhost:3000/products
###
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "name": "Producto 37",
    "description" : "Product 32 Description",
    "quantity": 32
}
###
GET {{api}}/4

###
DELETE {{api}}/3

###
PUT {{api}}/8
Content-Type: application/json

{
    "name": "Producto modificado 8",
    "description" : "Product modificado Descripti 8",
    "quantity": 99
}